# Generated by Django 6.0 on 2025-12-30 21:52

import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="profile",
            name="cropping",
            field=image_cropping.fields.ImageRatioField(
                "profile_picture",
                "400x400",
                adapt_rotation=False,
                allow_fullsize=False,
                free_crop=False,
                help_text=None,
                hide_image_field=False,
                size_warning=False,
                verbose_name="cropping",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="cropping",
            field=image_cropping.fields.ImageRatioField(
                "image",
                "800x450",
                adapt_rotation=False,
                allow_fullsize=False,
                free_crop=False,
                help_text=None,
                hide_image_field=False,
                size_warning=False,
                verbose_name="cropping",
            ),
        ),
    ]
