# Generated by Django 6.0 on 2025-12-30 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_contactmessage_profile_cropping_project_cropping"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="is_current",
            field=models.BooleanField(default=False),
        ),
    ]
