# Generated by Django 6.0 on 2025-12-31 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_projectimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skill",
            options={"ordering": ["category", "order", "name"]},
        ),
        migrations.AddField(
            model_name="skill",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
