/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContactForm: typeof import('./src/components/ContactForm.vue')['default']
    ExperienceTile: typeof import('./src/components/ExperienceTile.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    ProjectCard: typeof import('./src/components/ProjectCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skills: typeof import('./src/components/Skills.vue')['default']
  }
}
