/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ColdStartNotice: typeof import('./src/components/ColdStartNotice.vue')['default']
    ContactForm: typeof import('./src/components/ContactForm.vue')['default']
    ExperienceTile: typeof import('./src/components/ExperienceTile.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    ProjectCard: typeof import('./src/components/ProjectCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkeletonExperience: typeof import('./src/components/skeletons/SkeletonExperience.vue')['default']
    SkeletonHero: typeof import('./src/components/skeletons/SkeletonHero.vue')['default']
    SkeletonProjectCard: typeof import('./src/components/skeletons/SkeletonProjectCard.vue')['default']
    SkeletonSkills: typeof import('./src/components/skeletons/SkeletonSkills.vue')['default']
    Skills: typeof import('./src/components/Skills.vue')['default']
  }
}
